name: "Build and deploy Github pages"

on:
  push:
    branches:
      - master
    paths:
      - "manual/**"

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Install Python dependencies"
        run: |
          pip3 install -r requirements.txt

      - name: "Build Sphinx Doc"
        run: |
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/html/
